---
stages:
  - test
  - publish

.rust: &rust
  image: rust:latest
  cache:
    paths:
      - .cargo/
      - target/

test:fmt:
  stage: test
  <<: *rust
  before_script:
    - export CARGO_HOME="$(pwd)/.cargo"
    - rustup component add rustfmt
  script:
    - cargo fmt -- --check

test:lint:
  stage: test
  <<: *rust
  before_script:
    - export CARGO_HOME="$(pwd)/.cargo"
    - rustup component add clippy
  script:
    - cargo clippy --all-targets --all-features -- -D warnings

test:unit:
  stage: test
  <<: *rust
  before_script:
    - export CARGO_HOME="$(pwd)/.cargo"
  script:
    - cargo test

publish:
  stage: publish
  <<: *rust
  only:
    - /^v\d+.\d+.\d+$/
  before_script:
    - export CARGO_HOME="$(pwd)/.cargo"
    - cargo login ${CARGO_PUBLISH_TOKEN}
  script:
    - cargo publish
